### ISSUE TITLE
Install the uStreamer Debian package instead of building from source

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/ansible-role-ustreamer#100]
Related https://github.com/tiny-pilot/tinypilot/issues/1353
Blocked on https://github.com/tiny-pilot/ustreamer-debian/issues/4

### Requirements

  - Grab the uStreamer Debian package path from a `ustreamer-debian` release
  - Maintain building from source if the Debian package is not specified

    - Skip Ansible tasks that would otherwise be handled by the Debian package

**Comment by mtlynch** [comment]
I've cut https://github.com/tiny-pilot/ansible-role-ustreamer/releases/tag/1.4.0 so this should be unblocked now.
