### ISSUE TITLE
Fails to install OMX dependencies when not on Raspbian

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/ansible-role-ustreamer#55]
The [experimental/h264 branch is failing to build](https://app.circleci.com/pipelines/github/tiny-pilot/ansible-role-tinypilot/418/workflows/01278c25-cc7c-4c83-9712-3c109c562305/jobs/866?invite=true#step-104-395) because it can't install the [OMX dependency `libraspberrypi-dev`](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/02df15433e26183c738ea11fef7e55ecb2248b42/tasks/main.yml#L78-L81) on debian ([which is where we run the build tests](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/15413c4cf9d0f3419a7dab4785994a664a993a66/molecule/default/molecule.yml#L14)).

In the `experimental/h264` branch we [enable the `ustreamer_h264_sink` variable](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/f524271baef139caa599dcee1de9d3f1b49d08e0/vars/main.yml#L14) which [flags uStreamer to compile with OMX even if we're not running on Rasbian](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/02df15433e26183c738ea11fef7e55ecb2248b42/tasks/main.yml#L59).

**Comment by jdeanwallace** [comment]
### Possible solution
Only compile uStreamer with OMX when the OS is Raspbian. We'll also need to enforce that the OS is Raspbian when [validating that the H264 variables are in a consistent state](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/15413c4cf9d0f3419a7dab4785994a664a993a66/tasks/main.yml#L2-L10) because H264 options are only available when OMX is enabled.

**Comment by mtlynch** [comment]
Yeah, let's just require it to be Raspbian to compile OMX. That was our behavior before H264, so we might as well just keep it that way since we can't compile uStreamer otherwise.

**Comment by jdeanwallace** [comment]
> Yeah, let's just require it to be Raspbian to compile OMX.

Okay sure.

Also I just realized that the `experimental/h264` build will always fail because it's trying to use H264 uStreamer options on an OS that is not Raspbian. If we enforce H264 + Raspbian in ansible code or let uStreamer try startup with H264 options, the build will always fail as long as we're testing on Debian/Ubuntu.

Are we okay with letting the build fail on `experimental/h264` for now?

**Comment by mtlynch** [comment]
>Are we okay with letting the build fail on experimental/h264 for now?

Yep, that's fine. `experimental/h264` is optimized to make it easy for us to deploy the code to dev devices.

When we apply the H264 changes to `master`, we'll configure it so that the CircleCI build isn't relying on any OMX features.
